create extension if not exists "uuid-ossp";
create table if not exists public.profiles (id uuid primary key references auth.users (id) on delete cascade, full_name text not null, role text not null check (role in ('teacher','student')), student_code text unique, class_name text, school_name text default 'โรงเรียนวัดสามัคคีธรรม', created_at timestamptz not null default now());
create table if not exists public.materials (id uuid primary key default uuid_generate_v4(), title text not null, unit text not null, level text not null, material_type text not null check (material_type in ('PDF','VIDEO','IMG')), file_path text, cover_path text, published_at timestamptz not null default now(), created_by uuid references public.profiles (id));
create table if not exists public.submissions (id uuid primary key default uuid_generate_v4(), assignment_title text not null, student_name text not null, student_code text not null, file_path text, status text not null default 'รอตรวจ', submitted_at timestamptz not null default now());
create table if not exists public.scores (id uuid primary key default uuid_generate_v4(), student_code text not null, assessment_title text not null, score numeric not null check (score >= 0), max_score numeric not null check (max_score > 0), passed boolean not null default false, updated_at timestamptz not null default now(), unique (student_code, assessment_title));
create table if not exists public.student_roster_uploads (id uuid primary key default uuid_generate_v4(), class_name text not null, file_path text not null, file_name text not null, file_size integer not null, uploaded_at timestamptz not null default now());
insert into storage.buckets (id, name, public) values ('classroom-files', 'classroom-files', false) on conflict (id) do nothing;
alter table public.profiles enable row level security; alter table public.materials enable row level security; alter table public.submissions enable row level security; alter table public.scores enable row level security; alter table public.student_roster_uploads enable row level security;
create policy "profiles can read own profile" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "classroom materials readable" on public.materials for select to authenticated using (true);
create policy "classroom materials insertable" on public.materials for insert to authenticated with check (true);
create policy "classroom materials updateable" on public.materials for update to authenticated using (true) with check (true);
create policy "submissions readable" on public.submissions for select to authenticated using (true);
create policy "submissions insertable" on public.submissions for insert to authenticated with check (true);
create policy "scores readable" on public.scores for select to authenticated using (true);
create policy "scores insertable" on public.scores for insert to authenticated with check (true);
create policy "scores updateable" on public.scores for update to authenticated using (true) with check (true);
create policy "rosters insertable" on public.student_roster_uploads for insert to authenticated with check (true);
create policy "rosters readable" on public.student_roster_uploads for select to authenticated using (true);
create policy "classroom files readable" on storage.objects for select to authenticated using (bucket_id = 'classroom-files');
create policy "classroom files uploadable" on storage.objects for insert to authenticated with check (bucket_id = 'classroom-files');
